export const fetchJobDgreeCodes = "FETCH-JOB-DGREE";
export const fetchMainCodes = "FETCH-MAIN-CODES";
export const fetchCates = "FETCH-CATES"
export const fetchJobByCat = "FETCH-JOB-BY-CAT"
export const fetchSupBoxNamesandmanager = "FETCH-SUPBOX-NAMES-AND-MANAGER"
export const fetchJobGovern = "FETCH-JOB-GOVERN"
export const fetchEmpStationAndGovern = "FETCH-EMP-STATION-GOVERN"
export const fetchJobStation = "FETCH-JOB-STATION"
export const fetchDeps = "FETCH-DEPS"
export const fetchEmpByDeps = "FETCH-EMP-DEPS"
export const fetchEmpName = "FETCH-EMP-NAME"
export const fetchEmpAppraisal = "FETCH-EMP-APPRAISAL"
export const fetchEmpTrans = "FETCH-EMP-TRANS"
export const fetchEmpEdu = "FETCH-EMP-EDU"
export const fetchEmpNameByName = "FETCH-EMP-BY-NAME"
export const fetchavailjd = "FETCH-AVAIL-JD"
export const fetchCurrentjd = "FETCH-CURRENT-JD"
export const fetchavailsupbox = "FETCH-AVAIL-SUPBOX"
export const fetchupjd = "FETCH-UP-JD"
export const fetchEmpDetails = "FETCH-EMP-DETAILS"
export const fetchDownJd = "FETCH-DOWN-JD"
export const fetchEmpFamily = "FETCH-EMP-FAMILY"
export const fetchqn = "FETCH-Q-N"
export const fetchuneschool = "FETCH-UNE-SCHOOL"
export const fetchspecarabic = "FETCH-SPEC-ARABIC"
export const GET_ERRORS = "GET-ERRORS"
export const CLEAR_ERRORS = "CLEAR-ERRORS"
export const USER_LOADED = "USER-LOADED"
export const USER_LOADING = "USER-LOADING"
export const AUTH_ERROR = "AUTH-ERROR"
export const LOGIN_SUCCESS = "LOGIN-SUCCESS"
export const LOGIN_FAIL = "LOGIN-FAIL"
export const LOGOUT_SUCCESS = "LOGOUT-SUCCESS"
export const REGISTER_SUCCESS = "REGISTER-SUCCESS"
export const REGISTER_FAIL = "REGISTER-FAIL"
export const NEW_APPRAISAL = "NEW-APPRAISAL"
export const fetchemps = "FETCH-EMPS"
export const fetchgid = "FETCH-GID"
export const updatetrans = "UPDATE-TRANS"
export const updateAppraisal = "UPDATE-APPRAISAL"






